### ISSUE TITLE
【UI】不要になったボタン等を削除する

### ISSUE THREAD

**Issue by washogo** [if-tech-support/todo_team_2#136]
## 実装内容の説明
- 不要になったUIを削除する
## 実装予定のページ・コンポーネントのデザイン画像もしくはURL
<img width="894" alt="8a3b5bcb989d28efadb7e013c72f7e0a" src="https://user-images.githubusercontent.com/89339695/155685230-00c95bd4-1a3e-47ad-be4d-0699a9c7485b.png">

<img width="896" alt="335d96f2ad60add531014e29ac51eead" src="https://user-images.githubusercontent.com/89339695/155685215-ffe8f871-02cc-46d9-bfc7-ea141537489b.png">

<img width="897" alt="f91386d56cef67ae7ee3bac579f918e8" src="https://user-images.githubusercontent.com/89339695/155685200-448bd31e-811a-4fe5-b0ef-6d9506bb3d6c.png">
## TASK
- [ ] 一覧画面にある「draftボタン」と「trashボタン」と「ヘッダー右側にある日付」を削除する
- [ ] 新規作成画面にある「draftボタン」を削除する
- [ ] 詳細画面の「editボタン」を削除する

## その他・備考
-他にUI関連で整理が必要な箇所は随時追加する可能性あり。
